# Generated by Django 4.1.5 on 2023-01-29 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
